[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive", "unstable-doc"] }
terse_cli = { path = "../terse_cli" }

[[bin]]
name = "cli"
path = "main.rs"
